### ISSUE TITLE
requirement ارور نصب

### ISSUE THREAD

**Issue by Mahantor** [javadr/AparatPLD#1]
![Screenshot 2024-06-10 110121](https://github.com/javadr/AparatPLD/assets/91434001/c8e6031e-ed1b-48b7-a552-528bc86e0730)

**Comment by javadr** [comment]
You can replace the content of requirements.txt with the following:

```
rich
argparse
bs4
lxml_html_clean
requests_html
```

However, I should mention that this script no longer works because Aparat has changed its pages. Unfortunately, I don't have the time to work on it right now, but feel free to proceed and fix the issue. If you manage to resolve it, please make a pull request. ;D
